### ISSUE TITLE
Notifications are missing with the latest plugin and discourse

### ISSUE THREAD

**Issue by doomspork** [gdpelican/babble#245]
Howdy @gdpelican!  After we recently updated to discourse 1.9.0.beta17 and babble 3.1.7 I noticed along with the chat moving to either the left or right side the screen, that the notifications were gone.  Was this an intentional change or a bug?  It's been fascinating to see just how much impact the notifications had with chat engagement being non-existent in the last few days.  If this was an intentional change, would you be open to a PR to add notifications back as a configuration option?

**Comment by gdpelican** [comment]
Notifications were taken out because they were quite inaccurate when switching between channels (resulting in lots of negative numbers and other badness).

There's still an 'unread' indicator, although it's probably too subtle at the moment. I'd start off with some custom css to make the babble-icon-unread element stand out a bit more to see if that helps, and PR that if it does?

**Comment by SystemZ** [comment]
Sidebar chat is great but without badge with unread messages I can confirm engagement of my community is much lower than usual too. Would be awesome if unread indicator could be back.

**Comment by doomspork** [comment]
@gdpelican I'm not CSS pro but after playing around with the custom CSS we were able to create a more attention grabbing icon:

```css
#babble-icon-unread {
 i {
    -webkit-animation: pulse 2s infinite;
    -moz-animation: pulse 2s infinite;
    -o-animation: pulse 2s infinite;
    animation: pulse 2s infinite;
 }
}

@keyframes pulse {
  0% {
    color: #b7b7b7;

  }
  50% {
    color: #f42a00;
  }
  100% {
    color: #b7b7b7;
  }
}
```

While this is literally flashy, I still don't think it's as attention grabbing as the previous notifications were.  Perhaps instead of reflecting the unread count, the badge could just say "unread"?
